---PROMPT Creating tables.

CREATE TABLE LIBRARY_INFO (BOOK_ID Varchar PRIMARY KEY,
			   BOOK_TITLE VARCHAR(255),
			   BOOK_AUTHOR VARCHAR(255) NOT NULL,
			   BOOK_CATEGORY VARCHAR(200) NOT NULL
			  );


CREATE TABLE STUDENT_INFO (STUDENT_ID Varchar NOT NULL,
			   STUDENT_NAME VARCHAR(10)
			  );


CREATE TABLE BOOKS_ISSUED_INFO (STUDENT_ID Varchar NOT NULL,
				BOOK_ID Varchar NOT NULL,
				STATUS Varchar, ISSUED_STATUS Varchar, STUDENT_NAME varchar,
				FOREIGN KEY (BOOK_ID) REFERENCES LIBRARY_INFO(BOOK_ID) 
			       );


CREATE TABLE BOOKS_RETURN_INFO (STUDENT_ID Varchar NOT NULL,
				BOOK_TITLE VARCHAR(255),
				DUE_DAYS int,
				PENALTY_PER_DAY Float,
			        PENALTY_AMOUNT_PAID Float
			       );



--ALTER TABLE LIBRARY_INFO.

ALTER TABLE LIBRARY_INFO RENAME COLUMN BOOK_ID TO BOOKS_ID;

--ALTER TABLE STUDENT_INFO.

ALTER TABLE STUDENT_INFO
ALTER COLUMN STUDENT_NAME
SET DATA TYPE VARCHAR(200);

--ALTER TABLE BOOKS_ISSUED_INFO.

ALTER TABLE BOOKS_ISSUED_INFO
DROP COLUMN STUDENT_NAME;
