--PROMPT INSERTING INTO STUDENT_INFO 

Insert into Student_info (Student_Id,Student_Name) values ('SID1','Aadhya');
Insert into Student_info (Student_Id,Student_Name) values ('SID2','Aakash');
Insert into Student_info (Student_Id,Student_Name) values ('SID3','Aarav');
Insert into Student_info (Student_Id,Student_Name) values ('SID4','Aarushi');
Insert into Student_info (Student_Id,Student_Name) values ('SID5','Aarya');
Insert into Student_info (Student_Id,Student_Name) values ('SID6','Aashna');
Insert into Student_info (Student_Id,Student_Name) values ('SID7','Abha');
Insert into Student_info (Student_Id,Student_Name) values ('SID8','Abhijit');
Insert into Student_info (Student_Id,Student_Name) values ('SID9','Abhilasha');
Insert into Student_info (Student_Id,Student_Name) values ('SID10','Abhinav');
Insert into Student_info (Student_Id,Student_Name) values ('SID11','Aditi');
Insert into Student_info (Student_Id,Student_Name) values ('SID12','Advaita');
Insert into Student_info (Student_Id,Student_Name) values ('SID13','Agastya');
Insert into Student_info (Student_Id,Student_Name) values ('SID14','Aishani');
Insert into Student_info (Student_Id,Student_Name) values ('SID15','Aishwarya');
Insert into Student_info (Student_Id,Student_Name) values ('SID16','Akanksha');
Insert into Student_info (Student_Id,Student_Name) values ('SID17','Akash');
Insert into Student_info (Student_Id,Student_Name) values ('SID18','Akhil');
Insert into Student_info (Student_Id,Student_Name) values ('SID19','Akshara');
Insert into Student_info (Student_Id,Student_Name) values ('SID20','Akshay');
Insert into Student_info (Student_Id,Student_Name) values ('SID21','Alankrita');
Insert into Student_info (Student_Id,Student_Name) values ('SID22','Amaira');
Insert into Student_info (Student_Id,Student_Name) values ('SID23','Amartya');
Insert into Student_info (Student_Id,Student_Name) values ('SID24','Ambika');
Insert into Student_info (Student_Id,Student_Name) values ('SID25','Ameya');
Insert into Student_info (Student_Id,Student_Name) values ('SID26','Amisha');
Insert into Student_info (Student_Id,Student_Name) values ('SID27','Amolika');
Insert into Student_info (Student_Id,Student_Name) values ('SID28','Amrita');
Insert into Student_info (Student_Id,Student_Name) values ('SID29','Amruta');
Insert into Student_info (Student_Id,Student_Name) values ('SID30','Anagha');
Insert into Student_info (Student_Id,Student_Name) values ('SID31','Anahita');
Insert into Student_info (Student_Id,Student_Name) values ('SID32','Ananya');
Insert into Student_info (Student_Id,Student_Name) values ('SID33','Anchal');
Insert into Student_info (Student_Id,Student_Name) values ('SID34','Anika');
Insert into Student_info (Student_Id,Student_Name) values ('SID35','Aniket');
Insert into Student_info (Student_Id,Student_Name) values ('SID36','Anil');
Insert into Student_info (Student_Id,Student_Name) values ('SID37','Aniruddha');
Insert into Student_info (Student_Id,Student_Name) values ('SID38','Anisha');
Insert into Student_info (Student_Id,Student_Name) values ('SID39','Anjali');
Insert into Student_info (Student_Id,Student_Name) values ('SID40','Anjana');
Insert into Student_info (Student_Id,Student_Name) values ('SID41','Ankita');
Insert into Student_info (Student_Id,Student_Name) values ('SID42','Anmol');
Insert into Student_info (Student_Id,Student_Name) values ('SID43','Ansh');
Insert into Student_info (Student_Id,Student_Name) values ('SID44','Anshika');
Insert into Student_info (Student_Id,Student_Name) values ('SID45','Anshul');
Insert into Student_info (Student_Id,Student_Name) values ('SID46','Anuja');
Insert into Student_info (Student_Id,Student_Name) values ('SID47','Anujin');
Insert into Student_info (Student_Id,Student_Name) values ('SID48','Anupam');
Insert into Student_info (Student_Id,Student_Name) values ('SID49','Anuradha');
Insert into Student_info (Student_Id,Student_Name) values ('SID50','Anusha');
Insert into Student_info (Student_Id,Student_Name) values ('SID51','Anushka');
Insert into Student_info (Student_Id,Student_Name) values ('SID52','Anwesha');
Insert into Student_info (Student_Id,Student_Name) values ('SID53','Aparajita');
Insert into Student_info (Student_Id,Student_Name) values ('SID54','Apoorva');
Insert into Student_info (Student_Id,Student_Name) values ('SID55','Aradhana');
Insert into Student_info (Student_Id,Student_Name) values ('SID56','Aravind');
Insert into Student_info (Student_Id,Student_Name) values ('SID57','Archana');
Insert into Student_info (Student_Id,Student_Name) values ('SID58','Arhaan');
Insert into Student_info (Student_Id,Student_Name) values ('SID59','Arihant');
Insert into Student_info (Student_Id,Student_Name) values ('SID60','Arin');
Insert into Student_info (Student_Id,Student_Name) values ('SID61','Arjun');
Insert into Student_info (Student_Id,Student_Name) values ('SID62','Arnav');
Insert into Student_info (Student_Id,Student_Name) values ('SID63','Arnika');
Insert into Student_info (Student_Id,Student_Name) values ('SID64','Arohi');
Insert into Student_info (Student_Id,Student_Name) values ('SID65','Arpit');
Insert into Student_info (Student_Id,Student_Name) values ('SID66','Arshia');
Insert into Student_info (Student_Id,Student_Name) values ('SID67','Arushi');
Insert into Student_info (Student_Id,Student_Name) values ('SID68','Arya');
Insert into Student_info (Student_Id,Student_Name) values ('SID69','Asha');
Insert into Student_info (Student_Id,Student_Name) values ('SID70','Asher');
Insert into Student_info (Student_Id,Student_Name) values ('SID71','Ashish');
Insert into Student_info (Student_Id,Student_Name) values ('SID72','Ashmita');
Insert into Student_info (Student_Id,Student_Name) values ('SID73','Ashok');
Insert into Student_info (Student_Id,Student_Name) values ('SID74','Ashutosh');
Insert into Student_info (Student_Id,Student_Name) values ('SID75','Asmita');
Insert into Student_info (Student_Id,Student_Name) values ('SID76','Atharv');
Insert into Student_info (Student_Id,Student_Name) values ('SID77','Avani');
Insert into Student_info (Student_Id,Student_Name) values ('SID78','Avantika');
Insert into Student_info (Student_Id,Student_Name) values ('SID79','Avesh');
Insert into Student_info (Student_Id,Student_Name) values ('SID80','Ayush');
Insert into Student_info (Student_Id,Student_Name) values ('SID81','Bhakti');
Insert into Student_info (Student_Id,Student_Name) values ('SID82','Bhavana');
Insert into Student_info (Student_Id,Student_Name) values ('SID83','Bhavesh');
Insert into Student_info (Student_Id,Student_Name) values ('SID84','Bhavya');
Insert into Student_info (Student_Id,Student_Name) values ('SID85','Bhumika');
Insert into Student_info (Student_Id,Student_Name) values ('SID86','Chaitanya');
Insert into Student_info (Student_Id,Student_Name) values ('SID87','Chandra');
Insert into Student_info (Student_Id,Student_Name) values ('SID88','Chetan');
Insert into Student_info (Student_Id,Student_Name) values ('SID89','Chinmay');
Insert into Student_info (Student_Id,Student_Name) values ('SID90','Daksh');
Insert into Student_info (Student_Id,Student_Name) values ('SID91','Damini');
Insert into Student_info (Student_Id,Student_Name) values ('SID92','Darshan');
Insert into Student_info (Student_Id,Student_Name) values ('SID93','Deepa');
Insert into Student_info (Student_Id,Student_Name) values ('SID94','Deepak');
Insert into Student_info (Student_Id,Student_Name) values ('SID95','Devansh');
Insert into Student_info (Student_Id,Student_Name) values ('SID96','Devendra');
Insert into Student_info (Student_Id,Student_Name) values ('SID97','Devika');
Insert into Student_info (Student_Id,Student_Name) values ('SID98','Dhairya');
Insert into Student_info (Student_Id,Student_Name) values ('SID99','Dhananjay');
Insert into Student_info (Student_Id,Student_Name) values ('SID100','Dhanush');
Insert into Student_info (Student_Id,Student_Name) values ('SID101','Dhara');
Insert into Student_info (Student_Id,Student_Name) values ('SID102','Dhruv');
Insert into Student_info (Student_Id,Student_Name) values ('SID103','Divya');
Insert into Student_info (Student_Id,Student_Name) values ('SID104','Diya');
Insert into Student_info (Student_Id,Student_Name) values ('SID105','Drishti');
Insert into Student_info (Student_Id,Student_Name) values ('SID106','Durga');
Insert into Student_info (Student_Id,Student_Name) values ('SID107','Eeshan');
Insert into Student_info (Student_Id,Student_Name) values ('SID108','Eklavya');
Insert into Student_info (Student_Id,Student_Name) values ('SID109','Ekta');
Insert into Student_info (Student_Id,Student_Name) values ('SID110','Esha');
Insert into Student_info (Student_Id,Student_Name) values ('SID111','Gaurav');
Insert into Student_info (Student_Id,Student_Name) values ('SID112','Gayatri');
Insert into Student_info (Student_Id,Student_Name) values ('SID113','Geeta');
Insert into Student_info (Student_Id,Student_Name) values ('SID114','Girish');
Insert into Student_info (Student_Id,Student_Name) values ('SID115','Gopal');
Insert into Student_info (Student_Id,Student_Name) values ('SID116','Gunjan');
Insert into Student_info (Student_Id,Student_Name) values ('SID117','Gurpreet');
Insert into Student_info (Student_Id,Student_Name) values ('SID118','Harsh');
Insert into Student_info (Student_Id,Student_Name) values ('SID119','Harshita');
Insert into Student_info (Student_Id,Student_Name) values ('SID120','Hemant');


--UPDATE INTO STUDENT_INFO

Update Student_info set Student_name = 'Samruddhi' Where Student_Id = 'SID4';

--DELETE DATA FROM STUDENT_INFO

Delete from Student_info where Student_Id = ('SID5');

--SELECT DATA FROM STUDENT_INFO

Select * From Student_Info;