SELECT *
FROM LIBRARY_INFO;

SELECT *
FROM STUDENT_INFO;

SELECT *
FROM BOOKS_ISSUED_INFO;

SELECT *
FROM BOOKS_RETURN_INFO;



/*****************          JOINS          *******************/


SELECT *
FROM LIBRARY_INFO;

SELECT *
FROM STUDENT_INFO;

SELECT *
FROM BOOKS_ISSUED_INFO;



--Fetch the records which books has issued to students.

 /* INNER JOIN */
 
SELECT BOOKS_ISSUED_INFO.STUDENT_ID,
	STUDENT_INFO.STUDENT_NAME,
	LIBRARY_INFO.BOOK_TITLE
FROM ((BOOKS_ISSUED_INFO INNER JOIN STUDENT_INFO ON BOOKS_ISSUED_INFO.STUDENT_ID = STUDENT_INFO.STUDENT_ID)
						 INNER JOIN LIBRARY_INFO ON LIBRARY_INFO.BOOKS_ID = BOOKS_ISSUED_INFO.BOOK_ID);

--Fetch the addtional records from Books_issued_info.

 /* LEFT JOIN */
 
SELECT *
FROM BOOKS_ISSUED_INFO
LEFT JOIN BOOKS_RETURN_INFO ON BOOKS_ISSUED_INFO.STUDENT_ID = BOOKS_RETURN_INFO.STUDENT_ID;

--Fetch addtional records from student_info.

 /* RIGHT JOIN */
 
SELECT *
FROM BOOKS_ISSUED_INFO
RIGHT JOIN STUDENT_INFO ON STUDENT_INFO.STUDENT_ID = BOOKS_ISSUED_INFO.STUDENT_ID;

--Fetch All records from Student_info & Books_issued_info.

 /* FULL JOIN */
 
SELECT *
FROM STUDENT_INFO
FULL JOIN BOOKS_ISSUED_INFO ON BOOKS_ISSUED_INFO.STUDENT_ID = STUDENT_INFO.STUDENT_ID;

--Write a query to fetch the status_info and their issued_info corespodning to thier Book_id.

 /* SELF JOIN */
 
SELECT BOOK_INFO.BOOK_ID AS B_ID,
	BOOK_INFO.STATUS AS STATUS_INFO,
	BOOK_INFO.ISSUED_STATUS AS ISSUED_INFO,
	ISSUED_INFO.BOOK_ID AS B_ID,
	ISSUED_INFO.STATUS AS STATUS_INFO,
	ISSUED_INFO.ISSUED_STATUS AS ISSUED_INFO
FROM BOOK_ISSUED AS BOOK_INFO
JOIN BOOK_ISSUED AS ISSUED_INFO ON ISSUED_INFO.BOOK_ID = BOOK_INFO.BOOKS_ID;

--Write a query to fetch cartesian product.

 /* CROSS JOIN */
 
SELECT STUDENT_INFO.STUDENT_NAME,
	LIBRARY_INFO.BOOK_TITLE
FROM LIBRARY_INFO
CROSS JOIN STUDENT_INFO;



/**********   UNION AND UNION ALL   **********/ 


--Fetch the Orignal records from two table.

 /* UNION */
 
SELECT STUDENT_ID
FROM STUDENT_INFO
UNION
SELECT STUDENT_ID
FROM BOOKS_ISSUED_INFO;

--Fetch the all records from two table.

 /* UNION ALL */
 
SELECT STUDENT_ID
FROM STUDENT_INFO
UNION ALL
SELECT STUDENT_ID
FROM BOOKS_ISSUED_INFO;

--Fetch the orignal records under book_title from two table.

SELECT *
FROM LIBRARY_INFO;

SELECT *
FROM BOOKS_RETURN_INFO;

/* UNION */

SELECT *
FROM LIBRARY_INFO
WHERE BOOKS_ID = 'LB1'
	OR BOOKS_ID = 'LB10'
UNION
SELECT *
FROM BOOKS_ISSUED_INFO
WHERE BOOK_ID = 'LB1'
	OR BOOK_ID = 'LB10';

--Fetch the orignal records under book_title from two table.

 /* UNION */
 
SELECT *
FROM LIBRARY_INFO
WHERE BOOK_ID = 'LB1'
UNION 
SELECT *
FROM BOOKS_ISSUED_INFO
WHERE BOOK_ID = 'LB1';